package procedures

import (
	"github.com/twolodzko/gosch/eval"
)

var Procedures = eval.ProceduresGetter{
	"quote":         quote,
	"car":           car,
	"cdr":           cdr,
	"cons":          cons,
	"list":          list,
	"not":           not,
	"eq?":           eq,
	"and":           and,
	"or":            or,
	"=":             equal,
	"<":             lower,
	">":             greater,
	"define":        define,
	"set!":          set,
	"eval":          evalFn,
	"let":           let,
	"if":            ifFn,
	"cond":          cond,
	"else":          elseWord,
	"begin":         begin,
	"do":            do,
	"null?":         isNull,
	"pair?":         isPair,
	"number?":       isNumber,
	"integer?":      isInteger,
	"float?":        isFloat,
	"boolean?":      isBool,
	"string?":       isString,
	"symbol?":       isSymbol,
	"procedure?":    isProcedure,
	"nil?":          isNil,
	"+":             sum,
	"-":             dif,
	"*":             mul,
	"/":             div,
	"%":             mod,
	"//":            intDiv,
	"->float":       toFloat,
	"->int":         toInt,
	"string":        toString,
	"substring":     substring,
	"string-length": stringLength,
	"display":       display,
	"error":         raiseError,
	"load":          load,
	"debug":         debug,
	"map":           mapFn,
	"go":            goFn,
	"timeit":        timeit,
}
