package scheme

import (
	"github.com/twolodzko/gosch/eval"
	"github.com/twolodzko/gosch/macros"
	"github.com/twolodzko/gosch/types"
)

var Procedures = eval.ProceduresGetter{
	"-":             Dif,
	"->float":       ToFloat,
	"->int":         ToInt,
	"*":             Mul,
	"/":             Div,
	"//":            IntDiv,
	"%":             Mod,
	"+":             Sum,
	"<":             Lower,
	"=":             Equal,
	">":             Greater,
	"and":           And,
	"begin":         Begin,
	"boolean?":      IsBool,
	"car":           Car,
	"cdr":           Cdr,
	"cond":          Cond,
	"cons":          Cons,
	"debug":         Debug,
	"define-syntax": macros.DefineSyntax,
	"define":        Define,
	"display":       Display,
	"do":            Do,
	"else":          types.TRUE,
	"eq?":           Eq,
	"error":         Error,
	"eval":          Eval,
	"float?":        IsFloat,
	"go":            Go,
	"if":            If,
	"integer?":      IsInteger,
	"lambda":        NewLambda,
	"let":           Let,
	"list":          List,
	"load":          Load,
	"map":           Map,
	"nil?":          IsNil,
	"not":           Not,
	"null?":         IsNull,
	"number?":       IsNumber,
	"or":            Or,
	"pair?":         IsPair,
	"procedure?":    IsProcedure,
	"quasiquote":    Quasiquote,
	"quote":         Quote,
	"set!":          Set,
	"string-length": StringLength,
	"string?":       IsString,
	"string":        ToString,
	"substring":     Substring,
	"symbol?":       IsSymbol,
	"syntax-rules":  macros.NewSyntaxRules,
	"timeit":        Timeit,
	"unquote":       Unquote,
	"expand-macro":  macros.ExpandMacro,
	"vector":        Vector,
	"vector-length": VectorLength,
	"make-vector":   MakeVector,
	"vector-ref":    VectorRef,
	"vector-set!":   VectorSet,
	"vector->list":  VectorToList,
	"list->vector":  ListToVector,
	"vector?":       IsVector,
}
