package scheme

import (
	"github.com/twolodzko/gosch/eval"
	"github.com/twolodzko/gosch/scheme/extended_types"
	"github.com/twolodzko/gosch/scheme/macros"
	"github.com/twolodzko/gosch/scheme/primitives"
	"github.com/twolodzko/gosch/scheme/special_forms"
	"github.com/twolodzko/gosch/types"
)

var Procedures = eval.ProceduresGetter{
	"-":             primitives.Dif,
	"->float":       primitives.ToFloat,
	"->int":         primitives.ToInt,
	"*":             primitives.Mul,
	"/":             primitives.Div,
	"//":            primitives.IntDiv,
	"%":             primitives.Mod,
	"+":             primitives.Sum,
	"<":             primitives.Lower,
	"=":             primitives.Equal,
	">":             primitives.Greater,
	"and":           special_forms.And,
	"begin":         special_forms.Begin,
	"boolean?":      primitives.IsBool,
	"car":           primitives.Car,
	"cdr":           primitives.Cdr,
	"cond":          special_forms.Cond,
	"cons":          primitives.Cons,
	"debug":         primitives.Debug,
	"define-syntax": macros.DefineSyntax,
	"define":        special_forms.Define,
	"display":       primitives.Display,
	"do":            special_forms.Do,
	"else":          types.TRUE,
	"eq?":           primitives.Eq,
	"error":         primitives.Error,
	"eval":          special_forms.Eval,
	"expand-macro":  macros.ExpandMacro,
	"float?":        primitives.IsFloat,
	"gensym":        macros.Gensym,
	"go":            primitives.Go,
	"if":            special_forms.If,
	"integer?":      primitives.IsInteger,
	"lambda":        special_forms.NewLambda,
	"let":           special_forms.Let,
	"list->vector":  extended_types.ListToVector,
	"list":          primitives.List,
	"load":          special_forms.Load,
	"make-vector":   extended_types.MakeVector,
	"map":           primitives.Map,
	"nil?":          primitives.IsNil,
	"not":           special_forms.Not,
	"null?":         primitives.IsNull,
	"number?":       primitives.IsNumber,
	"or":            special_forms.Or,
	"pair?":         primitives.IsPair,
	"procedure?":    primitives.IsProcedure,
	"quasiquote":    special_forms.Quasiquote,
	"quote":         special_forms.Quote,
	"set!":          special_forms.Set,
	"string-length": extended_types.StringLength,
	"string?":       extended_types.IsString,
	"string":        extended_types.ToString,
	"substring":     extended_types.Substring,
	"symbol?":       primitives.IsSymbol,
	"syntax-rules":  macros.NewSyntaxRules,
	"timeit":        primitives.Timeit,
	"unquote":       special_forms.Unquote,
	"vector->list":  extended_types.VectorToList,
	"vector-length": extended_types.VectorLength,
	"vector-ref":    extended_types.VectorRef,
	"vector-set!":   extended_types.VectorSet,
	"vector?":       extended_types.IsVector,
	"vector":        extended_types.Vector,
	"macro":         special_forms.NewLispMacro,
	"define-macro":  special_forms.DefineMacro,
}
